server:
  port: 4004 # Gateway listens on port 4004

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Serve OpenAPI spec for patient-service via gateway
        - id: api-docs-patient-json
          uri: http://patient-service:4000
          predicates:
            - Path=/v3/api-docs/patient
          filters:
            - RewritePath=/v3/api-docs/patient,/v3/api-docs

        # Serve OpenAPI spec for auth-service via gateway
        - id: api-docs-auth-json
          uri: http://auth-service:4005
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth,/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: patient-service
        url: /v3/api-docs/patient
      - name: auth-service
        url: /v3/api-docs/auth